### PR TITLE
fix(.travis.yml): re-enable coverage upload script

### LINKED ISSUE #58: Re-enable codecov
Codecov has been disabled in our builds because we can't publish coverage results to codecov. We're getting this failure when we try to:

``` console
Failed to authenticate repository. Contact staff for more information. [validation-error-t3]
```

This build illustrates the failure: https://travis-ci.com/deis/steward/builds/29739591

This issue is for getting codecov publishing to work and un-commenting the `after_success` block (which publishes to codecov) in the `.travis.yml` file

### LINKED ISSUE #106: Enable codecov.io integration with CI

### PR DESCRIPTION
**Pull request by mboersma**
Uses the CODECOV_TOKEN private repo token stored in Travis CI.

Closes #58.
Closes #106.

### CODE REVIEW

**Comment by mboersma** [comment]
I rebased and re-ran this, but it fails in Travis CI with:
```
$ make test-cover docker-build
15:33:07 INFO   test_driver.go:38 Leasing k8s cluster from k8s-claimer.champagne.deis.com for 1200 seconds...
15:33:07 ERROR  test_driver.go:41 Error leasing k8s cluster: invalid status code for endpoing (POST http://k8s-claimer.champagne.deis.com/lease): 401
exit status 1
make: *** [test-cover] Error 1
```
Is this still a relevant change for steward, or should I close it? cc: @krancour.

**Comment by arschles** [comment]
@mboersma having code coverage would be great still! the failure is due to a change to our integration test infrastructure. The failure is ok since this PR doesn't make any semantic changes that need to be tested.

If you'd like to see it succeed, create a PR from a branch in the deis repository. This is a known limitation, which I'll be creating an issue for.

**Comment by mboersma** [comment]
> If you'd like to see it succeed, create a PR from a branch in the deis repository.

Excellent, will do. My fork of steward seems a bit...forked anyway because of the private -> public transition, so I want to recreate it. GitHub doesn't recognize it as an existing fork even once I made it public as well...

**Comment by arschles** [comment]
Created https://github.com/deis/steward/issues/230 to track the work to enable integration tests on forks

**Comment by mboersma** [comment]
Closing in favor of #233, fingers crossed.

**Pull request closed without merging**
